# Generated by Django 4.2.11 on 2026-02-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='amount_pledged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
