# Generated by Django 4.2.11 on 2026-02-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0002_sponsor_amount_pledged'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sponsor_logos/'),
        ),
    ]
