# Generated by Django 4.2.11 on 2026-02-23 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sponsorships', '0003_sponsor_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='sponsor',
            name='feedback_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='feedback_type',
            field=models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places_visited', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.AddField(
            model_name='sponsor',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsors', to='sponsorships.place'),
        ),
    ]
