# Generated by Django 4.2.11 on 2026-02-23 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0004_alter_sponsor_options_sponsor_feedback_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
    ]
